version: 2.1

jobs:
  run-test:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: "Install sequelize-cli, ts-node"
          command: "sudo npm i -g sequelize-cli && sudo npm i -g ts-node"
      - run:
          name: "Test"
          command: "npm run test"

workflows:
  test-workflow:
    jobs:
      - run-test
