version: 2.1

jobs:
  run-test:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: "Test"
          command: "npm run test"

workflows:
  test-workflow:
    jobs:
      - run-test
